// <auto-generated />
using System;
using BaseASP.NET_CORE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaseASP.NET_CORE.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210306143123_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaseASP.NET_CORE.Entities.HeThong.NhatKy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CAP_DO_ID");

                    b.Property<string>("DU_LIEU");

                    b.Property<Guid>("GUID");

                    b.Property<string>("IP_ADDRESS");

                    b.Property<string>("MO_TA");

                    b.Property<DateTime>("NGAY_TAO");

                    b.Property<string>("NOI_DUNG");

                    b.Property<string>("PAGE_URL");

                    b.Property<string>("PHAN_LOAI");

                    b.Property<string>("TEN_DANG_NHAP");

                    b.Property<string>("TEN_DAY_DU");

                    b.Property<string>("UNG_DUNG");

                    b.HasKey("ID");

                    b.ToTable("NhatKys");
                });
#pragma warning restore 612, 618
        }
    }
}
